### ISSUE TITLE
integration in f110-gym, request release tracks as individual zip files

### ISSUE THREAD

**Issue by luigiberducci** [f1tenth/f1tenth_racetracks#3]
Hi,
I am raising this issue to integrate all the work done on these racetracks in [`f1tenth_gym`](https://github.com/f1tenth/f1tenth_gym).

I think of two options for that:
- using **git submodules** and having `f1tenth_racetrack` as a submodule of `f1tenth_gym`, but it offers poor usability because the user should clone the report and then init and update the submodules
- add these tracks in a public **release** such that we can automatically download them without any effort from the user (see example in [racecar_gym](https://github.com/axelbr/racecar_gym/releases/tag/tracks-v1.0.0))

The second option is more convenient in my opinion, so it would be great if you can consider this request.

On a minor note, there is a black space in the folder name `Mexico City`.

Thanks,
Luigi

**Comment by hzheng40** [comment]
I'll probably package all the track files into a tarball and host it on `api.f1tenth.org`. Then it could be downloaded with requests and unzipped.
We can periodically update the tar hosted, but I don't think the content of the racetracks gets updated very often.
Let me know what you think. I'll get it started.

**Comment by luigiberducci** [comment]
Sounds good to me, thanks

**Comment by hzheng40** [comment]
The blank space of in mexico city file names should be fixed on the `deploy` branch where the release is from.
Also the ingestion should be addressed by [f1tenth_gym/pull/82](https://github.com/f1tenth/f1tenth_gym/pull/82). 
Closing for now.
